sudo: false
language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
services:
    - docker
before_install:
    - docker run --name arango -d -p 8529:8529 -e ARANGO_ROOT_PASSWORD=passwd arangodb/arangodb:3.3.8
    - docker cp tests/static/service.zip arango:/tmp/service.zip
install:
    - pip install flake8 mock pytest pytest-cov python-coveralls sphinx sphinx_rtd_theme
    - pip install .
script:
    - python -m flake8
    - python -m sphinx -b doctest docs build
    - python -m sphinx -b html -W docs build
    - py.test --complete -s -v --cov=arango
after_success:
    - coveralls
