from arango.exceptions.base import ArangoError
from arango.exceptions.aql import *
from arango.exceptions.async import *
from arango.exceptions.batch import *
from arango.exceptions.collection import *
from arango.exceptions.cursor import *
from arango.exceptions.database import *
from arango.exceptions.document import *
from arango.exceptions.graph import *
from arango.exceptions.index import *
from arango.exceptions.job import *
from arango.exceptions.pregel import *
from arango.exceptions.server import *
from arango.exceptions.task import *
from arango.exceptions.transaction import *
from arango.exceptions.user import *
from arango.exceptions.wal import *
